# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170921_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 22, 14, 31, 59, 266829), null=True, verbose_name='生日'),
        ),
    ]
