# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170917_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=1, upload_to='teacher/%Y/%m', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
