# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('primary', '初级'), ('middle', '中级'), ('high', '高级')], max_length=7, verbose_name='难度'),
        ),
    ]
