# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', max_length=300, verbose_name='访问视频地址'),
        ),
    ]
