# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_comment',
            new_name='CourseComment',
        ),
    ]
